/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about',
      icon: 'fluent:book-information-24-regular',
      order: 99
    }
  },
  {
    name: 'biz',
    path: '/biz',
    component: 'layout.base',
    meta: {
      title: 'biz',
      i18nKey: 'route.biz'
    },
    children: [
      {
        name: 'biz_auditorconfig',
        path: '/biz/auditorconfig',
        component: 'view.biz_auditorconfig',
        meta: {
          title: 'biz_auditorconfig',
          i18nKey: 'route.biz_auditorconfig'
        }
      },
      {
        name: 'biz_collabdashboard',
        path: '/biz/collabdashboard',
        component: 'view.biz_collabdashboard',
        meta: {
          title: 'biz_collabdashboard',
          i18nKey: 'route.biz_collabdashboard'
        }
      },
      {
        name: 'biz_collaborder',
        path: '/biz/collaborder',
        component: 'view.biz_collaborder',
        meta: {
          title: 'biz_collaborder',
          i18nKey: 'route.biz_collaborder'
        }
      },
      {
        name: 'biz_collabordersend',
        path: '/biz/collabordersend',
        component: 'view.biz_collabordersend',
        meta: {
          title: 'biz_collabordersend',
          i18nKey: 'route.biz_collabordersend'
        }
      },
      {
        name: 'biz_collabpartner',
        path: '/biz/collabpartner',
        component: 'view.biz_collabpartner',
        meta: {
          title: 'biz_collabpartner',
          i18nKey: 'route.biz_collabpartner'
        }
      },
      {
        name: 'biz_collabprofile',
        path: '/biz/collabprofile',
        component: 'view.biz_collabprofile',
        meta: {
          title: 'biz_collabprofile',
          i18nKey: 'route.biz_collabprofile'
        }
      },
      {
        name: 'biz_customer',
        path: '/biz/customer',
        component: 'view.biz_customer',
        meta: {
          title: 'biz_customer',
          i18nKey: 'route.biz_customer'
        }
      },
      {
        name: 'biz_customeraccount',
        path: '/biz/customeraccount',
        component: 'view.biz_customeraccount',
        meta: {
          title: 'biz_customeraccount',
          i18nKey: 'route.biz_customeraccount'
        }
      },
      {
        name: 'biz_customerbill',
        path: '/biz/customerbill',
        component: 'view.biz_customerbill',
        meta: {
          title: 'biz_customerbill',
          i18nKey: 'route.biz_customerbill'
        }
      },
      {
        name: 'biz_customerbillprint',
        path: '/biz/customerbillprint',
        component: 'view.biz_customerbillprint',
        meta: {
          title: 'biz_customerbillprint',
          i18nKey: 'route.biz_customerbillprint'
        }
      },
      {
        name: 'biz_customerreconciliation',
        path: '/biz/customerreconciliation',
        component: 'view.biz_customerreconciliation',
        meta: {
          title: 'biz_customerreconciliation',
          i18nKey: 'route.biz_customerreconciliation'
        }
      },
      {
        name: 'biz_dashboard',
        path: '/biz/dashboard',
        component: 'view.biz_dashboard',
        meta: {
          title: 'biz_dashboard',
          i18nKey: 'route.biz_dashboard'
        }
      },
      {
        name: 'biz_datahealth',
        path: '/biz/datahealth',
        component: 'view.biz_datahealth',
        meta: {
          title: 'biz_datahealth',
          i18nKey: 'route.biz_datahealth'
        }
      },
      {
        name: 'biz_home',
        path: '/biz/home',
        component: 'view.biz_home',
        meta: {
          title: 'biz_home',
          i18nKey: 'route.biz_home'
        }
      },
      {
        name: 'biz_myprinttask',
        path: '/biz/myprinttask',
        component: 'view.biz_myprinttask',
        meta: {
          title: 'biz_myprinttask',
          i18nKey: 'route.biz_myprinttask'
        }
      },
      {
        name: 'biz_myrepairtask',
        path: '/biz/myrepairtask',
        component: 'view.biz_myrepairtask',
        meta: {
          title: 'biz_myrepairtask',
          i18nKey: 'route.biz_myrepairtask'
        }
      },
      {
        name: 'biz_notification',
        path: '/biz/notification',
        component: 'view.biz_notification',
        meta: {
          title: 'biz_notification',
          i18nKey: 'route.biz_notification'
        }
      },
      {
        name: 'biz_operationlog',
        path: '/biz/operationlog',
        component: 'view.biz_operationlog',
        meta: {
          title: 'biz_operationlog',
          i18nKey: 'route.biz_operationlog'
        }
      },
      {
        name: 'biz_order',
        path: '/biz/order',
        component: 'view.biz_order',
        meta: {
          title: 'biz_order',
          i18nKey: 'route.biz_order'
        }
      },
      {
        name: 'biz_orderadjustment',
        path: '/biz/orderadjustment',
        component: 'view.biz_orderadjustment',
        meta: {
          title: 'biz_orderadjustment',
          i18nKey: 'route.biz_orderadjustment'
        }
      },
      {
        name: 'biz_orderlog',
        path: '/biz/orderlog',
        component: 'view.biz_orderlog',
        meta: {
          title: 'biz_orderlog',
          i18nKey: 'route.biz_orderlog'
        }
      },
      {
        name: 'biz_performancesettlement',
        path: '/biz/performancesettlement',
        component: 'view.biz_performancesettlement',
        meta: {
          title: 'biz_performancesettlement',
          i18nKey: 'route.biz_performancesettlement'
        }
      },
      {
        name: 'biz_printer',
        path: '/biz/printer',
        component: 'view.biz_printer',
        meta: {
          title: 'biz_printer',
          i18nKey: 'route.biz_printer'
        }
      },
      {
        name: 'biz_printhall',
        path: '/biz/printhall',
        component: 'view.biz_printhall',
        meta: {
          title: 'biz_printhall',
          i18nKey: 'route.biz_printhall'
        }
      },
      {
        name: 'biz_printmonthlycost',
        path: '/biz/printmonthlycost',
        component: 'view.biz_printmonthlycost',
        meta: {
          title: 'biz_printmonthlycost',
          i18nKey: 'route.biz_printmonthlycost'
        }
      },
      {
        name: 'biz_printtask',
        path: '/biz/printtask',
        component: 'view.biz_printtask',
        meta: {
          title: 'biz_printtask',
          i18nKey: 'route.biz_printtask'
        }
      },
      {
        name: 'biz_productcostrule',
        path: '/biz/productcostrule',
        component: 'view.biz_productcostrule',
        meta: {
          title: 'biz_productcostrule',
          i18nKey: 'route.biz_productcostrule'
        }
      },
      {
        name: 'biz_producttype',
        path: '/biz/producttype',
        component: 'view.biz_producttype',
        meta: {
          title: 'biz_producttype',
          i18nKey: 'route.biz_producttype'
        }
      },
      {
        name: 'biz_profitcenter',
        path: '/biz/profitcenter',
        component: 'view.biz_profitcenter',
        meta: {
          title: 'biz_profitcenter',
          i18nKey: 'route.biz_profitcenter'
        }
      },
      {
        name: 'biz_profitcenterorder',
        path: '/biz/profitcenterorder',
        component: 'view.biz_profitcenterorder',
        meta: {
          title: 'biz_profitcenterorder',
          i18nKey: 'route.biz_profitcenterorder'
        }
      },
      {
        name: 'biz_receivableitem',
        path: '/biz/receivableitem',
        component: 'view.biz_receivableitem',
        meta: {
          title: 'biz_receivableitem',
          i18nKey: 'route.biz_receivableitem'
        }
      },
      {
        name: 'biz_repairer',
        path: '/biz/repairer',
        component: 'view.biz_repairer',
        meta: {
          title: 'biz_repairer',
          i18nKey: 'route.biz_repairer'
        }
      },
      {
        name: 'biz_repairhall',
        path: '/biz/repairhall',
        component: 'view.biz_repairhall',
        meta: {
          title: 'biz_repairhall',
          i18nKey: 'route.biz_repairhall'
        }
      },
      {
        name: 'biz_repairreview',
        path: '/biz/repairreview',
        component: 'view.biz_repairreview',
        meta: {
          title: 'biz_repairreview',
          i18nKey: 'route.biz_repairreview'
        }
      },
      {
        name: 'biz_repairtask',
        path: '/biz/repairtask',
        component: 'view.biz_repairtask',
        meta: {
          title: 'biz_repairtask',
          i18nKey: 'route.biz_repairtask'
        }
      },
      {
        name: 'biz_repairtaskdetail',
        path: '/biz/repairtaskdetail',
        component: 'view.biz_repairtaskdetail',
        meta: {
          title: 'biz_repairtaskdetail',
          i18nKey: 'route.biz_repairtaskdetail'
        }
      },
      {
        name: 'biz_resource',
        path: '/biz/resource',
        component: 'view.biz_resource',
        meta: {
          title: 'biz_resource',
          i18nKey: 'route.biz_resource'
        }
      },
      {
        name: 'biz_systemconfig',
        path: '/biz/systemconfig',
        component: 'view.biz_systemconfig',
        meta: {
          title: 'biz_systemconfig',
          i18nKey: 'route.biz_systemconfig'
        }
      },
      {
        name: 'biz_workbench',
        path: '/biz/workbench',
        component: 'view.biz_workbench',
        meta: {
          title: 'biz_workbench',
          i18nKey: 'route.biz_workbench'
        }
      }
    ]
  },
  {
    name: 'demo',
    path: '/demo',
    component: 'layout.base',
    meta: {
      title: 'demo',
      i18nKey: 'route.demo'
    },
    children: [
      {
        name: 'demo_demo',
        path: '/demo/demo',
        component: 'view.demo_demo',
        meta: {
          title: 'demo_demo',
          i18nKey: 'route.demo_demo'
        }
      },
      {
        name: 'demo_tree',
        path: '/demo/tree',
        component: 'view.demo_tree',
        meta: {
          title: 'demo_tree',
          i18nKey: 'route.demo_tree'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base',
    meta: {
      title: 'log',
      i18nKey: 'route.log'
    },
    children: [
      {
        name: 'log_financeoperationlog',
        path: '/log/financeoperationlog',
        component: 'view.log_financeoperationlog',
        meta: {
          title: 'log_financeoperationlog',
          i18nKey: 'route.log_financeoperationlog'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'resource',
    path: '/resource',
    component: 'layout.base',
    meta: {
      title: 'resource',
      i18nKey: 'route.resource'
    },
    children: [
      {
        name: 'resource_tenantresourceorder',
        path: '/resource/tenantresourceorder',
        component: 'view.resource_tenantresourceorder',
        meta: {
          title: 'resource_tenantresourceorder',
          i18nKey: 'route.resource_tenantresourceorder'
        }
      },
      {
        name: 'resource_tenantresourceusagelog',
        path: '/resource/tenantresourceusagelog',
        component: 'view.resource_tenantresourceusagelog',
        meta: {
          title: 'resource_tenantresourceusagelog',
          i18nKey: 'route.resource_tenantresourceusagelog'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.blank$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      localIcon: 'menu-system',
      order: 1
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu',
          localIcon: 'menu-tree-table',
          order: 3
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config',
          constant: true,
          hideInMenu: true,
          icon: 'hugeicons:configuration-01'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'tool',
    path: '/tool',
    component: 'layout.base',
    meta: {
      title: 'tool',
      i18nKey: 'route.tool',
      localIcon: 'menu-tool',
      order: 4
    },
    children: [
      {
        name: 'tool_gen',
        path: '/tool/gen',
        component: 'view.tool_gen',
        meta: {
          title: 'tool_gen',
          i18nKey: 'route.tool_gen',
          localIcon: 'menu-code',
          order: 2
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'material-symbols:account-circle-full',
      hideInMenu: true
    }
  },
  {
    name: 'wx',
    path: '/wx',
    component: 'layout.base',
    meta: {
      title: 'wx',
      i18nKey: 'route.wx'
    },
    children: [
      {
        name: 'wx_templatemessagelog',
        path: '/wx/templatemessagelog',
        component: 'view.wx_templatemessagelog',
        meta: {
          title: 'wx_templatemessagelog',
          i18nKey: 'route.wx_templatemessagelog'
        }
      }
    ]
  }
];
